spring:
  datasource:
    hikari:
      # 외부 클라이언트에서는 jdbc:h2:tcp://localhost:9092/~/h2db/url-shortener 로 접근한다.
      jdbc-url: jdbc:h2:file:~/h2db/url-shortener
      username: sa
  jpa:
    hibernate:
      ddl-auto: validate
  freemarker:
    suffix: .html
app:
  base-domain: http://localhost:8080